//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjTelefe.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalabrasBuscadas
    {
        public int Id { get; set; }
        public string PalabraBuscada { get; set; }
        public System.DateTime FechaBusqueda { get; set; }
    }
}
